<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>impl</string>
		<string>sign</string>
	</array>
	<key>name</key>
	<string>Opal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.opal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\-\-).*$</string>
			<key>name</key>
			<string>comment.line.double-dash.opal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/\*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*/)</string>
			<key>name</key>
			<string>comment.block.opal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(FUN)\s+(\w*)\s*(\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.opal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.opal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.opal</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.parameters.opal</string>
			<key>end</key>
			<string>($)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.opal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\*\*|\-&gt;</string>
					<key>name</key>
					<string>punctuation.seperator.parameters.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>nat|char|real|denotation|bool</string>
					<key>name</key>
					<string>variable.parameter.opal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(DEF)\s+(\w*)\s*(?:(\())?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.opal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.opal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(\)))?\s*(==)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.opal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.begin.opal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.seperator.parameters.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w*</string>
					<key>name</key>
					<string>variable.parameter.opal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\\\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.function.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.seperator.parameters.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w*</string>
					<key>name</key>
					<string>variable.parameter.opal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(SORT)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.sort.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.sort.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\w*\b</string>
					<key>name</key>
					<string>entity.name.type.opal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=\w+(?:\s*::\s*\w+)*\s*::\s+&lt;&gt;)</string>
			<key>end</key>
			<string>(&lt;&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.end.opal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.list.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(::)</string>
					<key>name</key>
					<string>punctuation.separator.list.opal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#evaluable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#evaluable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Nat|Char|Real|Denotation)\b</string>
			<key>name</key>
			<string>support.type.opal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>evaluable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\b(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|64|128|256|512|1024|100|1000|10000|100000|1000000)\b)|\"\d+\"!</string>
					<key>name</key>
					<string>constant.numeric.integer.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\"(\d*\.\d+|\d+\.\d*)\"!</string>
					<key>name</key>
					<string>constant.numeric.real.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\"0x\h+\"!</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\".*\"!</string>
					<key>name</key>
					<string>invalid.illegal.unexpected-number.opal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.opal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.opal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.opal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(SIGNATURE|IMPLEMENTATION)\b</string>
					<key>name</key>
					<string>keyword.meta.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(^\s*IMPORT|\b(ONLY|COMPLETELY))\b</string>
					<key>name</key>
					<string>keyword.control.import.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(IF|THEN|ELSE|FI)\b</string>
					<key>name</key>
					<string>keyword.control.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(LET|IN|WHERE)\b</string>
					<key>name</key>
					<string>keyword.other.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;=|&gt;=|&lt;|&gt;|\|=|(?&lt;!=)=(?!=))</string>
					<key>name</key>
					<string>keyword.operator.comparison.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+|\-|\*|/|\bdiv\b|\^|\bpow\b|%|\bmod\b)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.opal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(map|filter|zip|sqrt)\b</string>
					<key>name</key>
					<string>support.function.builtin.opal</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.opal</string>
	<key>uuid</key>
	<string>3da0f3f0-8b32-41c9-857c-ce9be39b99d4</string>
</dict>
</plist>
