<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>SysDefs</string>
	</array>
	<key>name</key>
	<string>Opal SysDefs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.opalsysdefs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$</string>
			<key>name</key>
			<string>comment.line.number-sign.opalsysdefs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Z_]+)\s*(\+?=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.opalsysdefs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.keyvaluepair.opalsysdefs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n|(?=#)</string>
			<key>name</key>
			<string>meta.keyvaluepair.opalsysdefs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>.*</string>
			<key>name</key>
			<string>invalid.illegal.justkidding.noseriously.whoknows.opalsysdefs</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\$)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.dollar.opalsysdefs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.opalsysdefs</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.other.opalsysdefs</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.opalsysdefs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.thingy.opalsysdefs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\w\?!\_])*</string>
					<key>name</key>
					<string>string.other.opalsysdefs</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.opalsysdefs</string>
	<key>uuid</key>
	<string>3da0f3f0-8b32-41c9-857c-ce9be39b99d5</string>
</dict>
</plist>
